# Generated by Django 4.2.2 on 2023-06-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="categories",
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                default="L",
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
