# Generated by Django 4.2.2 on 2023-06-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_remove_task_categories_alter_task_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Not Started"),
                    ("C", "Completed"),
                    ("IP", "In Progress"),
                ],
                default="P",
                max_length=2,
            ),
        ),
    ]
