# Generated by Django 4.2.2 on 2023-06-22 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_remove_task_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="complete",
        ),
    ]
